'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VB_FullDemo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property dtwain32() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dtwain32", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [Sources]
        '''
        '''[SourceXferWaitInfo]
        '''WIA-*=1000
        '''
        '''[FlatbedOnly]
        '''WIA-*=1
        '''
        '''[TwainLoopPeek]
        '''FUJITSU*=1
        '''PaperStream*=1
        '''
        '''[OCRLibrary]
        '''Transym=TOCRDLL.DLL
        '''
        '''[CheckFeederStatus]
        '''CheckStatus=0
        '''
        '''[Language]
        '''default=english
        '''
        '''[ImageFile]
        '''resample=1
        '''
        '''[Miscellaneous]
        '''resourcecheck=1
        '''
        '''[PaperDetectionStatus]
        '''AV176*=1 ähnelt.
        '''</summary>
        Friend ReadOnly Property dtwain321() As String
            Get
                Return ResourceManager.GetString("dtwain321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property dtwain32u() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dtwain32u", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [Sources]
        '''
        '''[SourceXferWaitInfo]
        '''WIA-*=1000
        '''
        '''[FlatbedOnly]
        '''WIA-*=1
        '''
        '''[TwainLoopPeek]
        '''FUJITSU*=1
        '''PaperStream*=1
        '''
        '''[OCRLibrary]
        '''Transym=TOCRDLL.DLL
        '''
        '''[CheckFeederStatus]
        '''CheckStatus=0
        '''
        '''[Language]
        '''default=english
        '''
        '''[ImageFile]
        '''resample=1
        '''
        '''[Miscellaneous]
        '''resourcecheck=1
        '''
        '''[PaperDetectionStatus]
        '''AV176*=1 ähnelt.
        '''</summary>
        Friend ReadOnly Property dtwain64() As String
            Get
                Return ResourceManager.GetString("dtwain64", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property dtwain64u() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dtwain64u", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property twain32() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("twain32", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property twain64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("twain64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die !!Warning!!  Do not edit this file!  This file contains various initialization values used by the Dynarithmic TWAIN Library.
        '''5.7.0
        '''1 1 1 28 15 0
        '''1 1 2 28 15 0
        '''1 1 3 28 15 0
        '''1 1 6 28 15 2
        '''1 1 7 28 15 0
        '''1 1 8 28 14 0
        '''1 1 9 28 15 0
        '''1 1 10 28 15 0
        '''1 1 11 28 15 0
        '''1 1 2561 28 15 0
        '''1 2 1537 3 15 0
        '''1 3 1026 5 11 0
        '''1 3 3 5 3 0
        '''1 3 4 5 3 0
        '''1 3 5 5 2 7
        '''1 3 1025 5 7 0
        '''1 3 1027 5 7 0
        '''1 12 1 1 11 0
        '''1 12 6 1 11 0
        '''1 13 1 2 11 0
        '''1 14 2049 4 27 0
        '''1 14 2050 4 27 0
        '''1 14 2051 4 27 0
        '''1 14 2052 4 27 0
        '''1  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twaininfo() As String
            Get
                Return ResourceManager.GetString("twaininfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die english
        '''french
        '''spanish
        '''dutch
        '''german
        '''greek
        '''italian
        '''portuguese_br
        '''romanian
        '''russian
        '''portuguese
        '''simplified_chinese
        '''traditional_chinese
        '''japanese
        '''korean ähnelt.
        '''</summary>
        Friend ReadOnly Property twainlanguage() As String
            Get
                Return ResourceManager.GetString("twainlanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Geen fout
        '''1 NULL Raam Hanteert
        '''2 Herinnering Allocation Mislukking
        '''3 Kwalijken DLL Hanteert
        '''4 Kwalijken Bron Hanteert
        '''5 TWAIN. DLL niet Grondend
        '''6 Kwalijken TWAIN. DLL
        '''7 Kwalijken Sessie Hanteert
        '''8 Kwalijken Twain Manager
        '''9 Niet laden TWAIN. DLL
        '''10 Niet open TWAIN bron
        '''11 Niet afsluiten TWAIN bron
        '''12 TWAIN bron before uitgevoerd bevel.
        '''27 Niet voleindigde scan.   X/Y Resolutions want verschillende waarden
        '''28 Kwalijkene File Namen Gespecificeerd
        '''32 TWAIN-drieling niet uitgevoerd. Ongeldige T [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_dutch() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_dutch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 No Error
        '''1 NULL Window Handle
        '''2 Memory Allocation Failure
        '''3 Invalid DLL Handle
        '''4 Invalid Source Handle
        '''5 TWAIN Data Source Manager (DSM) Not Found
        '''6 Invalid TWAIN.DLL
        '''7 Invalid Session Handle
        '''8 Invalid Twain Manager
        '''9 Could not load TWAIN.DLL
        '''10 Could not open TWAIN source
        '''11 Could not close TWAIN source
        '''12 TWAIN source must be opened before executing command.
        '''27 Could not complete scan.  X/Y Resolutions set for different values
        '''28 Invalid File Name Specified
        '''32 TWAIN triplet not executed.  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_english() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_english", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Aucune erreur
        '''1 Fenêtre inefficace Manipule
        '''2 Raté D&apos;Affectation De Mémoire
        '''3 Mauvais DLL Manipule
        '''4 Mauvaise Source Manipule
        '''5 DLL de Twain. ne Fonde pas
        '''6 DLL mauvais de TWAIN.
        '''7 Mauvaise Séance Manipule
        '''8 Mauvais Tenancier De Twain
        '''9 Ne pouvions pas charger TWAIN. DLL
        '''10 Ne pouvions pas ouvrir TWAIN la source
        '''11 Ne pouvions pas fermer TWAIN la source
        '''12 Source de Twain doit être ouverte au-devant exécuter le commande
        '''27 Ne pouvions pas parachever échographie.   X/Y ou Résolutions met pour  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_french() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_french", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Kein Fehler
        '''1 Ungültiges Fenster Handle
        '''2 Speicherallokierung fehlgeschlagen
        '''3 Ungültiges DLL Handle
        '''4 Ungültiges Twain Source Handle
        '''5 TWAIN.DLL nicht gefunden
        '''6 Ungültige TWAIN.DLL
        '''7 Ungültiges Session Handle
        '''8 Ungültiger Twain Manager
        '''9 TWAIN.DLL Konnte nicht geladen werden
        '''10 TWAIN Quelle konnte nicht geöffnet werden
        '''11 TWAIN Quelle konnte nicht geschlossen werden
        '''12 TWAIN Quelle muß geöffnet werden bevor dieser Befehl ausgeführt werden kann.
        '''27 Scanvorgang konnte nicht vollständig ausgef [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_german() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_german", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Καμία Σφάλμα  
        '''1 NULL Χειριστής Παραθύρου  
        '''2 Αποτυχία Κατανομής Μνήμης  
        '''3 Μη Έγκυρος Χειριστής DLL  
        '''4 Μη Έγκυρος Χειριστής Πηγής  
        '''5 Ο Διαχειριστής Πηγής Δεδομένων TWAIN (DSM) δεν βρέθηκε  
        '''6 Μη Έγκυρο TWAIN.DLL  
        '''7 Μη Έγκυρος Χειριστής Συνεδρίας  
        '''8 Μη Έγκυρος Διαχειριστής Twain  
        '''9 Δεν ήταν δυνατή η φόρτωση του TWAIN.DLL  
        '''10 Δεν ήταν δυνατή η ανοίγμα της πηγής TWAIN  
        '''11 Δεν ήταν δυνατή η κλείσιμο της πηγής TWAIN  
        '''12 Η πηγή TWAIN πρέπει να είναι ανοιχτή πριν εκτελέσετε την εντολή.  
        '''27 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_greek() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_greek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Nessun errore
        '''1 NULL Finestra Maneggia
        '''2 Memoria Allocazione Fallimento
        '''3 Invalido DLL Maneggia
        '''4 Invalido Fonte Maneggia
        '''5 TWAIN. DLL non Basa
        '''6 Invalid TWAIN. DLL
        '''7 Invalido Seduta Maneggia
        '''8 Invalid Twain Dirigente
        '''9 Non colmando TWAIN. DLL
        '''10 Non aprendo TWAIN Fonte
        '''11 Non chiudendo TWAIN Fonte
        '''12 TWAIN Fonte apra avanti eseguendo comando.
        '''27 Non finendo scan.   X/Y o Risolutezze calo da diverso valute
        '''28 Invalido Archivia Nome Precisato
        '''32 triplet TWAIN non eseguito.  Twain Manager non [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_italian() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_italian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 エラーなし  
        '''1 NULL ウィンドウハンドル  
        '''2 メモリ割り当て失敗  
        '''3 無効な DLL ハンドル  
        '''4 無効なソースハンドル  
        '''5 TWAIN データソースマネージャー (DSM) が見つかりません  
        '''6 無効な TWAIN.DLL  
        '''7 無効なセッションハンドル  
        '''8 無効な Twain マネージャー  
        '''9 TWAIN.DLL を読み込めませんでした  
        '''10 TWAIN ソースを開けませんでした  
        '''11 TWAIN ソースを閉じることができませんでした  
        '''12 TWAIN ソースはコマンドを実行する前に開かなければなりません。  
        '''27 スキャンを完了できませんでした。 X/Y 解像度が異なる値に設定されています  
        '''28 指定されたファイル名が無効です  
        '''32 TWAINトリプレットが実行されませんでした。 無効なTwainマネージャー
        '''1000 ***  
        '''1001 無効な DTWAIN_HANDLE  
        '''1002 無効な DTWAIN_SOURCE  
        '''1003 無効な DTWAIN_ARRAY  
        '''1004 不正な DTW [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_japanese() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_japanese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 오류 없음  
        '''1 NULL 창 핸들  
        '''2 메모리 할당 실패  
        '''3 잘못된 DLL 핸들  
        '''4 잘못된 소스 핸들  
        '''5 TWAIN 데이터 소스 관리자(DMS)를 찾을 수 없음  
        '''6 잘못된 TWAIN.DLL  
        '''7 잘못된 세션 핸들  
        '''8 잘못된 Twain 관리자  
        '''9 TWAIN.DLL을 로드할 수 없음  
        '''10 TWAIN 소스를 열 수 없음  
        '''11 TWAIN 소스를 닫을 수 없음  
        '''12 TWAIN 소스는 명령을 실행하기 전에 열어야 합니다.  
        '''27 스캔을 완료할 수 없습니다. X/Y 해상도가 서로 다른 값으로 설정되어 있습니다.  
        '''28 잘못된 파일 이름이 지정되었습니다.  
        '''32 트윈 삼중주가 실행되지 않았습니다. 잘못된 트윈 관리자
        '''1000 ***  
        '''1001 잘못된 DTWAIN_HANDLE  
        '''1002 잘못된 DTWAIN_SOURCE  
        '''1003 잘못된 DTWAIN_ARRAY  
        '''1004 잘못된 DTWAIN_ARRAY 유형  
        '''1005 DTWAIN_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_korean() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_korean", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Sem Erro  
        '''1 Manipulador de Janela NULL  
        '''2 Falha na Alocação de Memória  
        '''3 Manipulador de DLL Inválido  
        '''4 Manipulador de Fonte Inválido  
        '''5 Gerenciador de Fonte de Dados TWAIN (DSM) Não Encontrado  
        '''6 TWAIN.DLL Inválido  
        '''7 Manipulador de Sessão Inválido  
        '''8 Gerenciador Twain Inválido  
        '''9 Não foi possível carregar TWAIN.DLL  
        '''10 Não foi possível abrir a fonte TWAIN  
        '''11 Não foi possível fechar a fonte TWAIN  
        '''12 A fonte TWAIN deve ser aberta antes de executar o comando.  
        '''27 Não foi possív [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_portuguese() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_portuguese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Nenhum erro
        '''1 Identificador de janela NULL
        '''2 Falha na alocação de memória
        '''3 Identificador de DLL inválido
        '''4 Identificador de origem inválido
        '''5 Gerenciador de fonte de dados TWAIN (DSM) não encontrado
        '''6 TWAIN.DLL inválida
        '''7 Identificador de sessão inválido
        '''8 Gerenciador Twain inválido
        '''9 Não foi possível carregar a TWAIN.DLL
        '''10 Não foi possível abrir o dispositivo TWAIN
        '''11 Não foi possível fechar o dispositivo TWAIN
        '''12 O dispositivo TWAIN deve ser aberto antes da execução do comando.
        '''27 Não foi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_portuguese_br() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_portuguese_br", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Nicio eroare  
        '''1 Mâner de fereastră NULL  
        '''2 Eșec la alocarea memoriei  
        '''3 Mâner DLL invalid  
        '''4 Mâner sursă invalid  
        '''5 Managerul sursei de date TWAIN (DSM) nu a fost găsit  
        '''6 TWAIN.DLL invalid  
        '''7 Mâner de sesiune invalid  
        '''8 Manager Twain invalid  
        '''9 Nu s-a putut încărca TWAIN.DLL  
        '''10 Nu s-a putut deschide sursa TWAIN  
        '''11 Nu s-a putut închide sursa TWAIN  
        '''12 Sursa TWAIN trebuie să fie deschisă înainte de a executa comanda.  
        '''27 Nu s-a putut finaliza scanarea. Rezoluțiile X/Y setate pen [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_romanian() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_romanian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Нет ошибок  
        '''1 Неверная дескриптор окна  
        '''2 Ошибка выделения памяти  
        '''3 Неверный дескриптор DLL  
        '''4 Неверный дескриптор источника  
        '''5 Менеджер источников данных TWAIN (DSM) не найден  
        '''6 Неверный TWAIN.DLL  
        '''7 Неверный дескриптор сессии  
        '''8 Неверный менеджер Twain  
        '''9 Не удалось загрузить TWAIN.DLL  
        '''10 Не удалось открыть источник TWAIN  
        '''11 Не удалось закрыть источник TWAIN  
        '''12 Источник TWAIN должен быть открыт перед выполнением команды.  
        '''27 Не удалось завершить сканирование. Разрешения X/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_russian() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_russian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 无错误  
        '''1 空窗口句柄  
        '''2 内存分配失败  
        '''3 无效的 DLL 句柄  
        '''4 无效的源句柄  
        '''5 找不到 TWAIN 数据源管理器 (DSM)  
        '''6 无效的 TWAIN.DLL  
        '''7 无效的会话句柄  
        '''8 无效的 Twain 管理器  
        '''9 无法加载 TWAIN.DLL  
        '''10 无法打开 TWAIN 源  
        '''11 无法关闭 TWAIN 源  
        '''12 必须在执行命令之前打开 TWAIN 源。  
        '''27 无法完成扫描。X/Y 分辨率设置为不同值  
        '''28 指定的文件名无效  
        '''32 TWAIN 三重奏未执行。Twain 管理器无效。
        '''1000 ***  
        '''1001 无效的 DTWAIN_HANDLE  
        '''1002 无效的 DTWAIN_SOURCE  
        '''1003 无效的 DTWAIN_ARRAY  
        '''1004 错误的 DTWAIN_ARRAY 类型  
        '''1005 DTWAIN_ARRAY 索引超出范围  
        '''1006 堆内存不足  
        '''1007 DTWAIN 无法创建 TWAIN 窗口  
        '''1008 无效的像素类型  
        '''1009 无效的 DTW [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_simplified_chinese() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_simplified_chinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 Sin errores
        '''1 Ventana nula Maneja
        '''2 El Fracaso De Asignación De Memoria
        '''3 Los DLL inválido Maneja
        '''4 Origena Inválida Maneja
        '''5 Los DLL TWAIN no Funda
        '''6 Le Invalid a la TWAIN DLL
        '''7 Sesión Inválida Maneja
        '''8 Le Invalid A Twain Gerente
        '''9 No le podríamos cargar a la TWAIN DLL
        '''10 No le podríamos abrir a TWAIN origen
        '''11 No le podríamos tapar a TWAIN origen
        '''12 Origen de TWAIN abre a ejecutar el mandato adelante.
        '''27 No podríamos completar la scan.   Los X/Y o los las Resoluciones sienta para los valore [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_spanish() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_spanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 0 無錯誤  
        '''1 空的視窗句柄  
        '''2 記憶體分配失敗  
        '''3 無效的 DLL 句柄  
        '''4 無效的來源句柄  
        '''5 找不到 TWAIN 數據來源管理器 (DSM)  
        '''6 無效的 TWAIN.DLL  
        '''7 無效的會話句柄  
        '''8 無效的 Twain 管理器  
        '''9 無法載入 TWAIN.DLL  
        '''10 無法打開 TWAIN 來源  
        '''11 無法關閉 TWAIN 來源  
        '''12 在執行命令之前必須打開 TWAIN 來源。  
        '''27 無法完成掃描。X/Y 分辨率設置為不同的值  
        '''28 指定的檔案名稱無效  
        '''32 TWAIN 三重奏未執行。Twain 管理器無效。
        '''1000 ***  
        '''1001 無效的 DTWAIN_HANDLE  
        '''1002 無效的 DTWAIN_SOURCE  
        '''1003 無效的 DTWAIN_ARRAY  
        '''1004 錯誤的 DTWAIN_ARRAY 類型  
        '''1005 DTWAIN_ARRAY 的索引超出範圍  
        '''1006 堆記憶體不足  
        '''1007 DTWAIN 無法創建 TWAIN 視窗  
        '''1008 無效的像素類型  
        '''1 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property twainresourcestrings_traditional_chinese() As String
            Get
                Return ResourceManager.GetString("twainresourcestrings_traditional_chinese", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
